### ISSUE TITLE
.vimsession getting replaced or merged together

### ISSUE THREAD

**Issue by arpanpal010** [ahri/vim-sesspit#1]
example project structure
/projects root
-- project1
-- -- .vimsession~
-- project2
-- -- .vimsession~

the problem i'm facing is that sometimes when i open project1 i see either project 2 files, or all files i opened from project1 and project2.

**Comment by ahri** [comment]
Hm, for some reason I didn't get a notification about you posting this issue, sorry! I'll have a look into it tomorrow morning. Thanks a lot for the replication steps.

**Comment by ahri** [comment]
I couldn't resist, so I tried to replicate your problem and can't, in fact the scenario you describe is exactly my normal usage of the plugin; I have a ~/repos dir under which I have projects.

I've checked over the code and can't see how it could happen as the search happens by traversing directories using ".."

``` vim
function! s:location()
        let testpath = ""
        while empty(testpath) || isdirectory(testpath)
                for marker in split(s:project_markers, ",")
                        let path = testpath . marker
                        if isdirectory(path) || filereadable(path)
                                return testpath . s:filename
                        endif
                endfor

                let testpath .= "../"
        endwhile

        return s:filename
endfunction
```

So in your example it ought to traverse up from "/projects root/project1" to "/projects root" and then give up if it's failed to find a .git dir, defaulting to using .vimsession~ in the current directory; it's not clever enough to go looking in other directories in the filesystem.

Perhaps I am not accurately recreating your environment; could you let me know the following:
1. whether you've configured sesspit via anything like:
   
   ``` vim
   sesspit#set_filename(".mysession")
   sesspit#set_sessionoptions("buffers,tabpages")
   sesspit#set_project_markers(".git,.svn,MY_PROJECT_MARKER")
   ```
2. is "/project root" at the root of your filesystem?
3. what OS are you using? I have access to Linux/Windows/OSX to test on

I'd really like to solve this for you!

**Comment by arpanpal010** [comment]
Hey sorry, I've been really crammed with a couple of things lately. Also, I think the reason was because I was switching sessions with vim by closing it when project1 was loaded, and re-opening it after cd-ing into the project2 directory, and somehow vim kept the location cached. 

Lately I started using a script that wraps around tmux to open vim, and all has been well on that front since. Now that I'm checking it, here's my sesspit config..let me know if there's anything wrong..

sesspit#set_filename(".vimsession")
sesspit#set_sessionoptions("buffers,tabpages,curdir,slash")
sesspit#set_project_markers(".git,.svn,.bzr")

also after 3-4 tries, I could not replicate the issue anymore, (the main reason I haven't checked back here), so marking this as closed for now. I'll get back to this if I see it again in future.

Thanks. :)

**Comment by ahri** [comment]
Well, I'm glad it seems to be working. Looking at your config I wonder if the "curdir" option might interfere with the algorithm I use. I'll have a play around and see if I can break it!

Thanks for letting me know that the issue is not bothering you now :)
